#!/bin/sh
cd `dirname -- $0`
DIR=`pwd`
DOCKERBIN=docker
DOCKERPROJECT=icinga2x

cd docker

$DOCKERBIN build -t $DOCKERPROJECT --rm .

command="/bin/bash"

$DOCKERBIN run -u `id -u` -v $DIR/docker/icinga2-conf:/etc/icinga2/conf.d/tests -t -i --rm $DOCKERPROJECT $command
